### PR TITLE
Update test_client.py to handle exceptions

### PR DESCRIPTION
**Pull request by fernandojsg**
I'm trying to use your test suite for a project that uses flask-restful and sqlalchemy.
I've noticed that I'm getting correctly every http code from the server but I got stuck with the 404 from sqlalchemy.

My code looks something like:

``` python
class UserAPI(restful.Resource):
    def get(self, id):
        user = User.query.get_or_404(id)
        return user.to_json()
....
```

If I send a non-valid `id` test will just break without catching the correct error code as it call `abort(404)` and throws an exception making the app to fail:

``` bash
ERROR: test_user (tests.test_api.TestAPI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vagrant/serverside/tests/test_api.py", line 68, in test_user
    rv, json = self.client.get('/user/%d' % user.id)
  File "/vagrant/serverside/tests/test_client.py", line 31, in get
    return self.send(url, 'GET', headers=headers)
  File "/vagrant/serverside/tests/test_client.py", line 25, in send
    rv = self.app.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 397, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 487, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/vagrant/serverside/app/api/v1/patient.py", line 13, in get
    patient = Patient.query.get_or_404(100)
  File "/usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py", line 410, in get_or_404
    abort(404)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/exceptions.py", line 576, in __call__
    raise self.mapping[code](*args, **kwargs)
NotFound: 404: Not Found
```

I've added an `try/catch` to handle this exceptions by creating a `ExceptionResponse` class that will fill the `status_code` in order to get correctly in your testing suite.

I hope it will be useful for someone.

### CODE REVIEW

**Comment by fernandojsg** [comment]
@miguelgrinberg do you think it's better just to close this pull request? 
As if it's merged into the main branch it should be changed also the way you manage the 404 errors from `assertRaises` to check error codes with `self.assertTrue(rv.status_code == 404)`
For me is no problem to change them if you want, or just leave it as is, as you prefer.

**Comment by miguelgrinberg** [comment]
@kile couple of things. This is, i think, a tiny bit cleaner:

```
with self.app.test_request_context(self.prefix + url, method=method, data=data,
                               headers=headers):
    try:
        rv = self.app.preprocess_request()
        if rv is None:
            rv = self.app.dispatch_request()
        rv = self.app.make_response(rv)
        rv = self.app.process_response(rv)
    except HTTPException as e:
        rv = self.app.handle_user_exception(e)
```

If you want to update this pull request with these latest changes then I think this is looking good to merge. You need to make the updates on your fork using `--amend` in your commit (to replace your original commit). Then you need to `git push -f` and that will update this PR and leave it clean, without the older stuff.

That will keep you as author and contributor. If you don't care, then I'm happy to take it from here, but then your contribution would not be visible in the history of the project.

**Comment by fernandojsg** [comment]
@miguelgrinberg thank you much for the tips.
I've changed the commit and I've modified also the test_api.py to modify the `assertRaises(BadRequest)` and check `rv.status_code==400` instead.

**Comment by fernandojsg** [comment]
Yes I thought the same, it's better to catch just HTTPExceptions as they're directly related to the REST api testing, and leave the rest of custom exceptions to be able to catch using the `assertRaises`.

(Que bueno, no sabía que fueras Argentino. Aprovecho para felicitarte por el magnífico trabajo que haces, yo he aprendido todo lo que se de flask gracias a tu libro, tu web y tus speechs en la apicon :))

**Pull request merged**
